CREATE DATABASE "userdb";
CREATE DATABASE "productdb";
CREATE DATABASE "cartdb";
CREATE DATABASE "orderdb";
CREATE DATABASE "paymentdb";

GRANT ALL PRIVILEGES ON DATABASE "userdb" TO admin;
GRANT ALL PRIVILEGES ON DATABASE "productdb" TO admin;
GRANT ALL PRIVILEGES ON DATABASE "cartdb" TO admin;
GRANT ALL PRIVILEGES ON DATABASE "orderdb" TO admin;
GRANT ALL PRIVILEGES ON DATABASE "paymentdb" TO admin;