server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. User Service (Login/Register) - KHÔNG Filter
        - id: user-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

        - id: user-secured
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        # 2. Product Service
        - id: product-service-secured
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
            - Method=POST,PUT,DELETE
          filters:
            - AuthenticationFilter

        - id: product-service-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
            - Method=GET

        # 3. Order Service - CÓ Filter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        # 4. Cart Service (Giỏ hàng) - CÓ Filter
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/** # Ví dụ: /cart/add, /cart/remove
          filters:
            - AuthenticationFilter

        # 5. Payment Service (Thanh toán) - CÓ Filter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/** # Ví dụ: /payment/create-url, /payment/callback
          filters:
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # THÊM ĐOẠN NÀY:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1