spring.application.name=payment-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/paymentdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8085
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka.instance.prefer-ip-address= true
vnpay.tmn-code=MK11214C
vnpay.hash-secret=4C5S3UEOZON2WTPEY81DXQCX5JCBN8P0
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8082/api/payment/vn-pay-callback
vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction