spring.application.name=user-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/userdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
jwt.secret=JVx1H56i2Z0K5BtTT1biLzjAfkpZpE+u8F8m+eX4pQk=
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka.instance.prefer-ip-address= true