spring.application.name=order-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/orderdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8084
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/
eureka.instance.prefer-ip-address= true

resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.PRODUCT-SERVICE.permitted-number-of-calls-in-half-open-state=3
resilience4j.timelimiter.instances.PRODUCT-SERVICE.timeout-duration=3s
resilience4j.retry.instances.PRODUCT-SERVICE.max-attempts=3
resilience4j.retry.instances.PRODUCT-SERVICE.wait-duration=1s

resilience4j.timelimiter.instances.USER-SERVICE.timeout-duration=5s
resilience4j.circuitbreaker.instances.USER-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.USER-SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.USER-SERVICE.wait-duration-in-open-state=20s
resilience4j.retry.instances.USER-SERVICE.max-attempts=3
resilience4j.retry.instances.USER-SERVICE.wait-duration=2s


resilience4j.timelimiter.instances.CART-SERVICE.timeout-duration=2s
resilience4j.circuitbreaker.instances.CART-SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.CART-SERVICE.failure-rate-threshold=40
resilience4j.circuitbreaker.instances.CART-SERVICE.wait-duration-in-open-state=10s
resilience4j.retry.instances.CART-SERVICE.max-attempts=2
resilience4j.retry.instances.CART-SERVICE.wait-duration=500ms